Fix: reactive login state handling
Accenture/Federated-Catalogue-Viewer pull request #7
Opened 2024-11-12 14:27 UTC by jxhnx

2025-01-02 12:08 UTC, FabianScheidt requested changes

2025-01-02 12:08 UTC, FabianScheidt commented on src/app/services/auth.service.ts
> +        if (this.demoUsername && this.demoPassword) {
Shouldn't we also call `this.logout()` if *demoUsername* and *demoPassword* are not set to retain the previous behaviour?

2025-01-06 19:51 UTC, jxhnx commented on src/app/services/auth.service.ts
> +        if (this.demoUsername && this.demoPassword) {
I do not see this behavior in the previous code, but I agree that it makes sense to add it .. just for login state consistency. https://github.com/Accenture/Federated-Catalogue-Viewer/pull/7/commits/6e2388acf469973bdb85ef7606b66f3cc2668302

2025-01-07 09:05 UTC, FabianScheidt approved these changes

2025-01-07 09:05 UTC, merged